genome:
    models:
      - WizardLMTeam/WizardMath-7B-V1.1
      - GAIR/Abel-7B-002
    merge_method: task_arithmetic
    base_model: augmxnt/shisa-gamma-7b-v1
    layer_granularity: 8 # sane default
    allow_negative_weights: true # useful with task_arithmetic
tasks:
  - name: mgsm_train
    weight: 1.0